---
name: cfn_nag
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: cfn_nag scan
        uses: stelligent/cfn_nag@master
        with:
          input_path: cloudformation
          extra_args: -o sarif
          output_path: cfn_nag.sarif
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: cfn_nag.sarif
